--1. Criar o banco de dados SISTEMA_ACADEMICO.
CREATE DATABASE SISTEMA_ACADEMICO;

--2. Usar o banco de dados SISTEMA_ACADEMICO.
USE SISTEMA_ACADEMICO;

--3. Criar a tabela TB_CARGO com as seguintes colunas:
CREATE TABLE TB_CARGO (
    COD_CAGO INT,
    CARGO VARCHAR(50) NOT NULL,
    CONSTRAINT PK_CARGO PRIMARY KEY (COD_CAGO)
)

--4. Criar a tabela TB_DISCIPLINA com as seguintes colunas:
CREATE TABLE TB_DISCIPLINA (
    COD_DISCIPLINA INT,
    DISCIPLINA VARCHAR(50) NOT NULL,
    CONSTRAINT PK_DISCIPLINA PRIMARY KEY (COD_DISCIPLINA)
)

--5. Criar a tabela TM_ALUNO com as seguintes colunas:
CREATE TABLE TM_ALUNO (
    COD_ALUNO INT IDENTITY(1,1),
    NOME VARCHAR(50) NOT NULL,
    CPF_ALUNO INT NOT NULL,
    COD_CARGO INT NOT NULL,
    END_ALUNO VARCHAR(60) NOT NULL,
    BAIRRO_ALUNO VARCHAR(20) NULL,
    CIDADE_ALUNO VARCHAR(20) NULL,
    ESTADO_ALUNO CHAR(2) NULL,
    CEP_ALUNO CHAR(8) NULL,
    FONE CHAR(11) NULL,
    STATUS_ALUNO CHAR(1),
    DATA_CAD_ALUNO DATE NOT NULL,
    CONSTRAINT PK_ALUNO_COD PRIMARY KEY(COD_ALUNO)
)

--6. Criar a tabela TM_PROFESSOR com as seguintes colunas:
CREATE TABLE TM_PROFESSOR (
    COD_PROFESSOR INT IDENTITY(1,1),
    NOME VARCHAR(50) NOT NULL,
    CPF_PROFESSOR INT NOT NULL,
    COD_CARGO INT NOT NULL,
    END_PROFESSOR VARCHAR(60) NOT NULL,
    BAIRRO_PROFESSOR VARCHAR(20) NULL,
    CIDADE_PROFESSOR VARCHAR(20) NULL,
    ESTADO_PROFESSOR CHAR(2) NULL,
    CEP_PROFESSOR CHAR(8) NULL,
    FONE CHAR(11) NULL,
    STATUS_PROFESSOR CHAR(1),
    DATA_CAD_PROFESSOR DATE NOT NULL,
    CONSTRAINT PK_PROFESSOR_COD PRIMARY KEY(COD_PROFESSOR)
)

-- 7. Na tabela TB_ALUNO, adicionar a constraint de chave estrangeira para a coluna COD_CARGO, referenciando a tabela TB_CARGO.
ALTER TABLE TB_ALUNO
ADD
CONSTRAINT FK_ALUNO_CODCARGO FOREIGN KEY(COD_CARGO)
REFERENCES TB_CARGO(COD_CARGO)

-- 8. Na tabela TB_ALUNO, adicionar a constraint CHECK para a coluna STATUS_ALUNO, permitindo apenas os valores 'A' (ativo) e 'I' (inativo).*/   
ALTER TABLE TB_ALUNO
ADD
CONSTRAINT CK_ALUNO_STATUS CHECK(STATUS_ALUNO IN ('A','I'))

/*9. Criar a tabela TB_ALUNO_DISCIPLINA para relacionar os alunos com as disciplinas, contendo as colunas:
• COD_ALUNO_DISCIP (chave primária)*/
CREATE TABLE TB_ALUNO_DISCIPLINA (
    COD_ALUNO_DISCIP INT NOT NULL,
    COD_ALUNI INT,
    COD_DISCIPLINA INT
)

/*10. Na tabela TB_ALUNO_DISCIPLINA, adicionar:
• Chave primária para a coluna COD_ALUNO_DISCIP
• Chave estrangeira para as colunas COD_ALUNO e COD_DISCIPLINA*/
ALTER TABLE TB_ALUNO_DISCIPLINA
ADD
CONSTRAINT PK_ALUNO_DISCIPLINA PRIMARY KEY(COD_ALUNO_DISCIP),
CONSTRAINT FK_ALUNO_DISCIPLINA_ALUNO FOREIGN KEY(COD_ALUNO) REFERENCES TM_ALUNO(COD_ALUNO),
CONSTRAINT FK_ALUNO_DISCIPLINA_DISCIPLINA FOREIGN KEY(COD_DISCIPLINA) REFERENCES TB_DISCIPLINA(COD_DISCIPLINA)


--11. Adicionar constraint UNIQUE na coluna CPF_ALUNO.
ALTER TABLE TB_ALUNO
ADD
CONSTRAINT UN_ALUNO_CPF UNIQUE(CPF_ALUNO)

--12. Por default, a coluna DATA_CAD_ALUNO deve receber a data atual.
ALTER TABLE TB_ALUNO 
ADD
CONSTAINT DF_ALUNO_DATACADAL
DEFAULT GETDATE() FOR DATA_CAD_ALUNO