-- Usar a base de dados PEDIDOS
USE PEDIDOS;

-- Exemplo 1: Criar view de produtos com fornecedores
CREATE VIEW VW_PRODUTO_FORNECEDOR AS
SELECT PR.ID_PRODUTO, PR.DESCRICAO, F.NOME AS FORNECEDOR
FROM TB_PRODUTO PR
LEFT JOIN TB_PROD_FORN PF ON PR.ID_PRODUTO = PF.ID_PRODUTO
LEFT JOIN TB_FORNECEDOR F ON PF.COD_FORN = F.COD_FORN;

-- Consultar a view
SELECT * FROM VW_PRODUTO_FORNECEDOR;

-- Exemplo 2: View de pedidos com detalhes
CREATE VIEW VW_PEDIDO_DETALHADO AS
SELECT P.NUM_PEDIDO, P.VLR_TOTAL, V.NOME AS VENDEDOR, C.NOME AS CLIENTE
FROM TB_PEDIDO P
INNER JOIN TB_VENDEDOR V ON P.CODVEN = V.CODVEN
INNER JOIN TB_CLIENTE C ON P.COD_CLI = C.COD_CLI;

-- Consultar a view
SELECT * FROM VW_PEDIDO_DETALHADO;

-- Nota: Views são consultas salvas. Para alterar, use ALTER VIEW ou DROP e CREATE.