-- Usar a base de dados PEDIDOS
USE PEDIDOS;

-- Exemplo 1: COUNT - Número de produtos
SELECT COUNT(*) AS TOTAL_PRODUTOS FROM TB_PRODUTO;

-- Exemplo 2: SUM - Valor total de pedidos
SELECT SUM(VLR_TOTAL) AS VALOR_TOTAL_PEDIDOS FROM TB_PEDIDO;

-- Exemplo 3: AVG - Salário médio dos empregados
SELECT AVG(SALARIO) AS SALARIO_MEDIO FROM TB_EMPREGADO WHERE SALARIO IS NOT NULL;

-- Exemplo 4: MAX/MIN - Preços máximo e mínimo
SELECT MAX(PRECO_VENDA) AS PRECO_MAX, MIN(PRECO_VENDA) AS PRECO_MIN FROM TB_PRODUTO;

-- Exemplo 5: GROUP BY - Total por vendedor
SELECT V.NOME, COUNT(P.NUM_PEDIDO) AS NUM_PEDIDOS, SUM(P.VLR_TOTAL) AS TOTAL_VENDIDO
FROM TB_VENDEDOR V
LEFT JOIN TB_PEDIDO P ON V.CODVEN = P.CODVEN
GROUP BY V.NOME;

-- Exemplo 6: HAVING - Vendedores com mais de 5 pedidos
SELECT V.NOME, COUNT(P.NUM_PEDIDO) AS NUM_PEDIDOS
FROM TB_VENDEDOR V
LEFT JOIN TB_PEDIDO P ON V.CODVEN = P.CODVEN
GROUP BY V.NOME
HAVING COUNT(P.NUM_PEDIDO) > 5;