-- Usar a base de dados PEDIDOS
USE PEDIDOS;

-- Exemplo 1: INNER JOIN - Pedidos com vendedores
SELECT P.NUM_PEDIDO, P.VLR_TOTAL, V.NOME AS VENDEDOR
FROM TB_PEDIDO P
INNER JOIN TB_VENDEDOR V ON P.CODVEN = V.CODVEN;

-- Exemplo 2: LEFT JOIN - Produtos com fornecedores
SELECT PR.ID_PRODUTO, PR.DESCRICAO, F.NOME AS FORNECEDOR
FROM TB_PRODUTO PR
LEFT JOIN TB_PROD_FORN PF ON PR.ID_PRODUTO = PF.ID_PRODUTO
LEFT JOIN TB_FORNECEDOR F ON PF.COD_FORN = F.COD_FORN;

-- Exemplo 3: JOIN com múltiplas tabelas - Itens de pedido com produto e pedido
SELECT IP.NUM_PEDIDO, PR.DESCRICAO, IP.QTD, IP.VLR_UNIT
FROM TB_ITENSPEDIDO IP
INNER JOIN TB_PRODUTO PR ON IP.ID_PRODUTO = PR.ID_PRODUTO
INNER JOIN TB_PEDIDO P ON IP.NUM_PEDIDO = P.NUM_PEDIDO;

-- Exemplo 4: FULL OUTER JOIN - Empregados e dependentes
SELECT E.NOME AS EMPREGADO, D.NOME AS DEPENDENTE
FROM TB_EMPREGADO E
FULL OUTER JOIN TB_DEPENDENTE D ON E.COD_EMP = D.COD_EMP;